name: WakaTime status update 

on:
  push:
    branches: main

jobs:
  update-readme:
    name: Experiment
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH: "main"
