name: WakaTime status update 

on:
  push:
    branches: main

jobs:
  update-readme:
    name: Experiment
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/experiment@main
        with:
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
